import '../styles/globals.css';
import Header from'../components/Header'
import ReduxProvider from "../redux/ReduxProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <ReduxProvider>

          <div><Header /></div>
            <main> {children}</main>
          </ReduxProvider>
        


        </div>

       
      </body>
    </html>
  );
}
