import '../styles/globals.css';
import Header from'../components/Header'
import ReduxProvider from "../redux/ReduxProvider";
import "@radix-ui/themes/styles.css";
import { Theme } from '@radix-ui/themes';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <ReduxProvider>
          <div><Header /></div>
            <Theme>
 
            <main> {children}</main>
            </Theme>

          </ReduxProvider>
        


        </div>

       
      </body>
    </html>
  );
}
